WITH PRODUCTION_CHANGE_CTE AS (
SELECT
	*,
    LAG(TOYS_PRODUCED, 1) OVER(ORDER BY PRODUCTION_DATE) AS PREVIOUS_DAY_PRODUCTION,
    TOYS_PRODUCED - LAG(TOYS_PRODUCED, 1) OVER(ORDER BY PRODUCTION_DATE) AS PRODUCTION_CHANGE
FROM
	TOY_PRODUCTION
)
SELECT
	*,
    ROUND(PRODUCTION_CHANGE / PREVIOUS_DAY_PRODUCTION::numeric, 2) * 100 AS PRODUCTION_CHANGE_PERCENTAGE
FROM
	PRODUCTION_CHANGE_CTE
ORDER BY
	ROUND(PRODUCTION_CHANGE / PREVIOUS_DAY_PRODUCTION::numeric, 2) * 100 DESC