with AVG_SPEED_PER_REINDEER AS (
select
	R.REINDEER_NAME,
    TS.EXERCISE_NAME,
    AVG(TS.SPEED_RECORD) AS AVG_SPEED_RECORD
from
	REINDEERS AS R
join 
	TRAINING_SESSIONS AS TS ON R.REINDEER_ID = TS.REINDEER_ID
where
	R.REINDEER_NAME != 'Rudolf'
group by
	1, 2
)
select
	REINDEER_NAME,
    ROUND(MAX(AVG_SPEED_RECORD)::numeric, 2),
    ROW_NUMBER() OVER(ORDER BY ROUND(MAX(AVG_SPEED_RECORD)::numeric, 2) DESC)
from
	AVG_SPEED_PER_REINDEER
group by
	REINDEER_NAME
order by
	ROUND(MAX(AVG_SPEED_RECORD)::numeric, 2) DESC
limit 3