WITH TOY_CATEGORY_AND_COMPLEXITY AS (
SELECT
	TOY_NAME,
    CASE
    	WHEN CATEGORY = 'outdoor' THEN 'Outside Workshop'
        WHEN CATEGORY = 'educational' THEN 'Learning Workshop'
        ELSE 'General Workshop'
	END AS TOY_CATEGORY,
    CASE
    	WHEN DIFFICULTY_TO_MAKE = 1 THEN 'Simple Gift'
        WHEN DIFFICULTY_TO_MAKE = 2 THEN 'Moderate Gift'
        ELSE 'Complex Gift'
	END AS COMPLEXITY
FROM
	TOY_CATALOGUE
),

TOY_AND_COLOR AS (
SELECT
	C.NAME,
    JSON_VALUE(WISHES, '$.first_choice') AS FIRST_CHOICE,
    JSON_VALUE(WISHES, '$.second_choice') AS SECOND_CHOICE,
	JSON_VALUE(WISHES, '$.colors[0]') AS FAV_COLOR,
	JSON_ARRAY_LENGTH(WISHES::json -> 'colors') AS NUMBER_OF_COLORS
FROM
	WISH_LISTS AS WL
JOIN CHILDREN AS C ON C.CHILD_ID = WL.CHILD_ID
)

SELECT
	TAC.NAME,
    TAC.FIRST_CHOICE,
    TAC.SECOND_CHOICE,
    TAC.FAV_COLOR,
    TAC.NUMBER_OF_COLORS,
    TCAC.COMPLEXITY,
    TCAC.TOY_CATEGORY
FROM
	TOY_AND_COLOR AS TAC
JOIN TOY_CATEGORY_AND_COMPLEXITY AS TCAC ON TAC.FIRST_CHOICE = TCAC.TOY_NAME
ORDER BY
	TAC.NAME
LIMIT 5




